version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: safevote
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safevote-net

  backend:
    image: mosesade/safevote-backend-backend:latest
    ports:
      - "15550:15550"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: safevote
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - safevote-net

volumes:
  postgres_data: {}

networks:
  safevote-net:
