apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
meta:
  name: safevote-backend-monitor
spec:
  selector:
    matchLabels:
      app: safevote-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
