apiVersion: apps/v1
kind: Deployment
metadata:
  name: safevote-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safevote-backend
  template:
    metadata:
      labels:
        app: safevote-backend
    spec:
      containers:
        - name: safevote-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: "{{ .Values.env.DB_HOST }}"
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_NAME
              value: "{{ .Values.env.DB_NAME }}"
---
apiVersion: v1
kind: Service
metadata:
  name: safevote-backend
spec:
  type: LoadBalancer
  ports:
    - port: 15550
      targetPort: 15550
  selector:
    app: safevote-backend
