name: SafeVote CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build Docker Image & Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRESS_DB: safevote
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Wait for PostgreSQL
        run: |
          until PGPASSWORD=password psql -h localhost -U postgres -c '\l'; do
            >&2 echo "PostgreSQL is unavailable - sleeping"
            sleep 5
          done

      - name: Create Database
        run: |
          export PGPASSWORD=password
          psql -h localhost -U postgres -c "CREATE DATABASE safevote"

      - name: Run Migrations Tests
        run: npx knex migrate:latest

      - name: Seed Test Data
        run: npx knex seed:run

      - name: Run Integration Tests
        run: npm test

  build-and-deploy:
    name: Build Docker Image and Deploy to Kubernetes
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses:  docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mosesade/safevote-backend:latest

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: kubectl
        run: |
          kubectl get pods -A

      # - name: SetUp Kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'latest'

      # - name: Configure Kube context
      #   run: |
      #     echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
      #     export KUBECONFIG=$(pwd)/kubeconfig
      #     echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV

      # - name: Test Kubectl connection
      #   run: |
      #     kubectl get nodes

      # - name: Install Helm
      #   uses: azure/setup-helm@v3
      #   with:
      #     version: v3.12.0

      # - name: Configure Kubernetes Context
      #   uses: azure/k8s-deploy@v1
      #   with:
      #     namespace: default
      #     manifests: |
      #       k8s/deployment.yaml
      #     images: |
      #       ${{ vars.DOCKERHUB_USERNAME }}/safevote-backend:latest

      # - name: Deploy with Helm
      #   run: |
      #     hellm repo add bitnami https://charts.bitami.com/bitnami
      #     helm dependency update ./helm/safevote-backend
      #     helm upgrade --install safevote-backend ./helm/safevote-backend \
      #       --set image.repository=${{ vars.DOCKERHUB_USERNAME }}/safevote-backend \
      #       --set image.tag=latest

      - name: Archive Integration Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: __tests__/results/
